---

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "release tag"
        require: true
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp:
          - 24.2.1-1
        elixir:
          - 1.13.4
        system:
          - ubuntu20.04
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: build
        env:
          ELIXIR: ${{ matrix.elixir }}
          OTP: ${{ matrix.otp }}
          SYSTEM: ${{ matrix.system }}
          ARCH: ${{ matrix.arch }}
        run: |
          docker run --rm \
            -v "$PWD":/build \
            -w /build \
            --platform="linux/$ARCH" \
            "ghcr.io/emqx/emqx-builder/5.0-17:${ELIXIR}-${OTP}-${SYSTEM}" \
            bash -euc "./.github/workflows/release.sh ${{ matrix.arch }}"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: releases
          retention-days: 1
          path: |
            _build/prod/*.tar.gz
  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: releases
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ github.event.inputs.release_tag || github.event.release.tag_name }}
          files: |
            _build/prod/*.tar.gz
...
